name: Generate TWRP Device Tree

on:
  workflow_dispatch:
    inputs:
      LIBRARY_NAME:
        description: 'Library name for the device tree'
        required: true
        default: 'Twrp_Device_Generator'
      IMG_URL:
        description: 'URL to recovery/boot image'
        required: true
        default: 'https://github.com/xiaoshizuzhang/action_build_twrp_device_tree/blob/master/recovery.img'

jobs:
  generate-device-tree:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3 \
          python3-pip \
          cpio \
          git \
          repo \
          zip \
          unzip
        
 
        
    - name: Download recovery image
      run: |
       mkdir twrp
        cd twrp
        repo init -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-8.1
        repo sync
        git clone https://github.com/XRedCubeX/twrp_meizu_m2note.git -b twrp-8.1 device/meizu/m2note
        git clone https://github.com/XRedCubeX/android_kernel_m2note -b o-8.1 kernel/meizu/m2note
        export ALLOW_MISSING_DEPENDENCIES=true
        . build/envsetup.sh
        lunch omni_m2note-eng
        mka recoveryimage
      
    

    - name: Create release with device tree
      uses: softprops/action-gh-release@v1
      with:
        files: DeviceTree_${{ github.run_number }}.zip
        name: TWRP_Device_Tree_${{ github.run_number }}
        tag_name: dt-${{ github.run_number }}
        body: |
          Automatically generated TWRP device tree
          Build run: ${{ github.run_number }}
          Source image: ${{ github.event.inputs.IMG_URL }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
